### ISSUE TITLE
Feature request-switch with threshold

### ISSUE THREAD

**Issue by gdotp01** [ecoen66/homebridge-solaredge-inverter#10]
Hi,
I love the plug-in thanks for developing it. One thing that I could see being helpful is a switch that flicks on when a threshold is exceeded. What I’d like to do is see when we are generating more than say 1kw and send a notification. Now I guess I could do this by setting an automation in Eve that looks at the Lux value and then flicks a dummy switch on but it would be neater if this was available within this plugin.

**Comment by ecoen66** [comment]
I'm going to leave that to the automation capabilities in Homekit (I prefer Home+ 4 instead of Eve for creating automations).
