### ISSUE TITLE
Option to display output in W

### ISSUE THREAD

**Issue by Cardo1** [ecoen66/homebridge-solaredge-inverter#13]
Hi there,

Thanks for making this plugin.  I’m using this together with a plugin for my SolaX PV system.  The SolaX plugin displays the output in W, rather than kW, which I personally prefer.  Would it be possible to have an option to display the output from this plugin in W, rather than kW?

Thanks.

**Comment by ecoen66** [comment]
Unfortunately, this is a limitation in the way that Apple's homeKit represents a LUX value over 10,000 -- It just rounds the value up to the next thousand. After 100,000 it rounds to just the hundred thousands (so 138,432 = 100,000).

Are you looking for an option for just the current production to be displayed in W/kW?  Or other production intervals as week (day, month, year...)?

**Comment by Cardo1** [comment]
> Unfortunately, this is a limitation in the way that Apple's homeKit represents a LUX value over 10,000 -- It just rounds the value up to the next thousand. After 100,000 it rounds to just the hundred thousands (so 138,432 = 100,000).
> 
> Are you looking for an option for just the current production to be displayed in W/kW? Or other production intervals as week (day, month, year...)?

Hi.  Thanks for the response.  Personally, I was after the option to display in W just for the current production, as this will (sadly) never be anywhere near 10,000!

**Comment by ecoen66** [comment]
Try version 0.2.0.

It will require changing the config.json file (or deleting the section in there for the plugin, and then re-adding it through the Config-UI-X).

**Comment by Cardo1** [comment]
> Try version 0.2.0.
> 
> It will require changing the config.json file (or deleting the section in there for the plugin, and then re-adding it through the Config-UI-X).

Excellent, thanks.  I’m assuming it’s working, though will need to wait for daylight to confirm!

One, thing, now that it’s dark, it’s showing “0.0001 lux”.  I gather that’s how it’s adjusting from kW to W?

**Comment by ecoen66** [comment]
Math sucks in Java.


Sent from Yahoo Mail for iPhone


On Wednesday, December 23, 2020, 11:40 AM, Cardo1 <notifications@github.com> wrote:





Try version 0.2.0.

It will require changing the config.json file (or deleting the section in there for the plugin, and then re-adding it through the Config-UI-X).


Excellent, thanks. I’m assuming it’s working, though will need to wait for daylight to confirm!

One, thing, now that it’s dark, it’s showing “0.0001 lux”. I gather that’s how it’s adjusting from kW to W?

**Comment by Cardo1** [comment]
Excellent.
![Uploading 523F4DEF-E216-4969-ADE1-56762F801E4D.png…]()

**Comment by Cardo1** [comment]
Excellent. 
![AB14C29F-1ED5-4F18-BF24-3965A4F7459C](https://user-images.githubusercontent.com/7265647/103080576-038bb880-45ce-11eb-9bd7-7269f93726c8.png)

**Comment by gdotp01** [comment]
Hi. Not sure what I’m doing wrong but I can’t get the new version to work. As far as I can see the config file is correct, I want it to show current today and total as before but it’s only showing g current (in watts) but it’s only showing current in HomeKit. (In 
![7972BE61-D1CD-4DCE-B7DB-D379BA14B771](https://user-images.githubusercontent.com/50060482/103087804-9b929d80-45e0-11eb-902f-93c3eff0cefe.jpeg)
![84F97656-A1CD-4A67-A529-072C59774DA4](https://user-images.githubusercontent.com/50060482/103087806-9cc3ca80-45e0-11eb-8f8c-d76ba9f2109f.jpeg)

eve or Home)

**Comment by gdotp01** [comment]
Just adding, it does appear to be fetching the correct info 
![30B263F8-D2D4-49AF-BC1F-EDBA511A0AB5](https://user-images.githubusercontent.com/50060482/103088029-6b97ca00-45e1-11eb-9826-271d9f2a4e1e.jpeg)

**Comment by ecoen66** [comment]
Try v. 0.2.1.  I did a little regression testing to make sure.  It should be fine now.

**Comment by gdotp01** [comment]
That’s working now thanks
