### ISSUE TITLE
New version reporting odd current power readings

### ISSUE THREAD

**Issue by Cardo1** [ecoen66/homebridge-solaredge-inverter#14]
I updated to version 0.2.2 last night, and unfortunately I’m now getting odd readings. It’s pulling the data correctly, however the numbers displayed in Homekit are completely different. 
During the day, the current power display was considerably higher than the actual reading, and now that the real power is 0W it’s still showing an output in Homekit.
![A4217103-A4DF-48BB-BFE1-8ACE76A6263B](https://user-images.githubusercontent.com/7265647/103444118-74ca0c00-4c5d-11eb-8ae6-b9f0b945a2fe.jpeg)
![F2AFA556-25FE-4B80-8178-2069C4762897](https://user-images.githubusercontent.com/7265647/103444119-7693cf80-4c5d-11eb-9c96-b4b39c7c94ad.png)

**Comment by ecoen66** [comment]
I am guessing that you are only using the plugin to show your "SolarEdge Generation" in HomeKit...  I'm not sure how you are applying that label to my plugin's Current Power indicator.  That does not look like my plugin.

The log does show output from my plugin?!?

It's working perfectly on my end.

**Comment by Cardo1** [comment]
> I am guessing that you are only using the plugin to show your "SolarEdge Generation" in HomeKit... I'm not sure how you are applying that label to my plugin's Current Power indicator. That does not look like my plugin.
> 
> The log does show output from my plugin?!?
> 
> It's working perfectly on my end.

I changed the name of the accessory in Homekit. 

It was working correctly on the previous version.

**Comment by Cardo1** [comment]
![EECA32EA-1769-44EE-8EDE-D10FF34C073D](https://user-images.githubusercontent.com/7265647/103444490-9082e180-4c60-11eb-822f-7a23d613c285.png)

**Comment by ecoen66** [comment]
Unfortunately, I have no idea.

**Comment by ecoen66** [comment]
Please try V 0.2.3.

**Comment by Cardo1** [comment]
> Please try V 0.2.3.

This appears to have fixed the issue. Thanks!

**Comment by ecoen66** [comment]
Good.  Thanks for opening the issue and sharing your screenshots.
