### ISSUE TITLE
Incorrect value at end of day

### ISSUE THREAD

**Issue by gdotp01** [ecoen66/homebridge-solaredge-inverter#15]
Thanks for the new version. It seems to be working  well but I’ve seen one issue. It’s now night but the Lux value was still reading a small  value. Following a homebridge restart it was set to 0 (almost) 

![2D7B22A7-7ED3-42FA-8364-CB64109061D9](https://user-images.githubusercontent.com/50060482/103465765-ab278a00-4d36-11eb-99a6-05381cbc5423.png)
![BC25736C-0EA4-4A94-AB6A-80032B6031A2](https://user-images.githubusercontent.com/50060482/103465767-acf14d80-4d36-11eb-85e3-377ef2cddaa6.png)

**Comment by ecoen66** [comment]
What was the value prior to the restart?  Significantly higher?

**Comment by ecoen66** [comment]
Sorry about that!  Please try V 0.2.3.

**Comment by gdotp01** [comment]
Looks to have worked today. Thanks
