### ISSUE TITLE
Issue with status reading being different to current power

### ISSUE THREAD

**Issue by kellery82** [ecoen66/homebridge-solaredge-inverter#16]
Hi,

First off, thanks very much for your work and this plugin. Very appreciative to have something available in HomeKit.

I’m running the latest version and notice that the status reading is showing a completely different value than current power and my SolarEdge app. I thought the lux reading on the outdoor page should show the same value as current power (I’m not worried about the difference from the SolarEdge app and current power)

![1BE680A2-A9D7-4BBA-A504-989C58D113D2](https://user-images.githubusercontent.com/73224765/103468857-b4e1d980-4d98-11eb-84b0-cfcd5bac82bc.jpeg)
![31B01E4C-CA32-43C5-975A-C4D1D628CD3A](https://user-images.githubusercontent.com/73224765/103468859-b90df700-4d98-11eb-8d27-afbea2992b45.jpeg)
![7FA3B171-BDE5-45B3-8135-2AFBE2DAC547](https://user-images.githubusercontent.com/73224765/103468861-b9a68d80-4d98-11eb-8ac0-ec7a233e8b59.jpeg)

Regards,

Kristopher

**Comment by ecoen66** [comment]
The difference between the app and the plugin's current power reading might be based on the update_interval value from the config.json in Homebridge.  You should be able to scroll back through the Homebridge log to see what values were grabbed from the API on the last call.

As for the Lux summary in the Outdoors room, that is a HomeKit function.  HomeKit averages all Lux readings in a room and shows that average as the room summary.  Think of it like having multiple temperature readings in a room...

If you want the room's summary to be correct, then you may want to use only the Current Power option in the plugin.  It is also possible to add a 2nd instance of the plugin with a different Name and Serial Number which includes all other readings that you wanted, but not Current Power.  That instance can be left in Default Room.

**Comment by kellery82** [comment]
Ah that makes perfect sense. My apologies for my ignorance 😊

**Comment by ecoen66** [comment]
If you wish to split the readings across multiple instances, it works best with V 0.2.4.

**Comment by gdotp01** [comment]
Actually I think the issue is that HomeKit for some reason takes the three Lux values and displays a mean average in the summary view
