### ISSUE TITLE
[RFE] change API call to collect more data

### ISSUE THREAD

**Issue by stepir** [ecoen66/homebridge-solaredge-inverter#2]
Hi @ecoen66 

wanted to check if you might be interested in evolving the code for gathering not just the overview of the site but some more information as the following:

**oveview** API return the following info:
`<overview>
<lastUpdateTime>2020-05-15 10:29:15</lastUpdateTime>
<lifeTimeData>
<energy>1.5900604E7</energy>
<revenue>4820.456</revenue>
</lifeTimeData>
<lastYearData>
<energy>3811718.0</energy>
</lastYearData>
<lastMonthData>
<energy>585475.0</energy>
</lastMonthData>
<lastDayData>
<energy>8780.0</energy>
</lastDayData>
<currentPower>
<power>1197.2842</power>
</currentPower>
<measuredBy>INVERTER</measuredBy>
</overview>`

the proposal is to use **currentPowerFlow** API instead which return the following info:
`<siteCurrentPowerFlow>
<updateRefreshRate>3</updateRefreshRate>
<unit>kW</unit>
<GRID>
<status>Active</status>
<currentPower>0.0</currentPower>
</GRID>
<LOAD>
<status>Active</status>
<currentPower>1.07</currentPower>
</LOAD>
<PV>
<status>Active</status>
<currentPower>2.53</currentPower>
</PV>
<STORAGE>
<status>Charging</status>
<currentPower>1.46</currentPower>
<chargeLevel>26</chargeLevel>
<critical>false</critical>
</STORAGE>
<connections>
<connection>
<from>PV</from>
<to>Load</to>
</connection>
<connection>
<from>PV</from>
<to>Storage</to>
</connection>
</connections>
</siteCurrentPowerFlow>`

currentPowerFlow could be then used to represent:
- a light sensor showing GRID consumption/feed (unit is KW although represented in lux)
- a light sensor showing HOUSE/SITE consumption (unit is KW although represented in lux)
- a light sensor showing PV production (unit is KW although represented in lux)
- a light sensor showing BATTERY load (unit is KW although represented in lux)
- a humidity sensor showing BATTERY state of charge (unit is %)

what do you think?

**Comment by ecoen66** [comment]
@stepir That sounds like it would work.  My inverter does not support that API, so I won’t be developing the code for that.

Feel free to create a fork off of my code and add what you need.

**Comment by stepir** [comment]
<img width="791" alt="Schermata 2020-05-16 alle 12 44 33" src="https://user-images.githubusercontent.com/36472935/82117831-3554bb00-9773-11ea-9e6e-113c1dceb487.png">

I've done it - but I have never coded before so was only able to do it given I just changed your. I don't it's properly written to publish it for others. 

Thanks anyway your work was very helpful!

**Comment by ecoen66** [comment]
@stepir That looks great!  You should go ahead and publish it so others can learn from it (and use it for their homes).  I would love to look at your code.  I was thinking of modifying my code to send actual kW day to HomeKit first the Eve app.  Eve has a lot more dat that it knows how to display, and it can track history as well.

For a good example of an Accessory that shows a little information in Home, but a lot of information in Eve, just add homebridge-ws to your homebridge.

**Comment by stepir** [comment]
I think you can use fakegato-history for it!

I've created a private repo for my code - here is the code. There is a lot of space of improvement - eg collecting the info once and pass it over the to the right accessories.

**Comment by Doorenbosch** [comment]
Hi, uploading it allows other to review and maybe improve it. But great job!

Best,

Frank

Send from my mobile device

**Comment by stepir** [comment]
thanks it's available here

https://github.com/stepir/homebridge-solaredge
