### ISSUE TITLE
Integrate modbus protocol for real-time data

### ISSUE THREAD

**Issue by Kubiac** [ecoen66/homebridge-solaredge-inverter#26]
Hi,

apparently some (maybe many) inverters support modbus tcp communications. There is a python lib that provides easy access to the data: https://github.com/nmakel/solaredge_modbus

This would be super useful to react in near realtime to changes in power generation.

Keep up the great work!

**Comment by matbe81** [comment]
Great idea !

**Comment by Kubiac** [comment]
For anyone who is interested, i wrote a new plugin that does exactly that: https://github.com/Kubiac/homebridge-solaredge-realtime
