### ISSUE TITLE
"Last month" and "Last Year" labels incorrect

### ISSUE THREAD

**Issue by matbe81** [ecoen66/homebridge-solaredge-inverter#27]
"Last month" actually refer to current month while "Last Year" actually refer to current year.

Is it possible to correct those labels?

**Comment by ecoen66** [comment]
Although this is standard SolarEdge labeling, I do agree. Updated in version 0.2.7.  I did not change the config.json variable names - to avoid users having to edit their configs.

**Comment by matbe81** [comment]
Thank you. 
When the release is planned?
Is it possible to have an alternative than displaying the values on Lux unit in place of the real one?
Does all the exposed data are shown in HomeKit?

Thanks again for your great work!

**Comment by ecoen66** [comment]
The new version was published before my previous response.  Apple HomeKit doesn't know how to display Watts. That's why I am using Lux.  Other apps like Eve can display many additional parameters and values (such as Watts), but I haven't found the time to mess with that.

**Comment by matbe81** [comment]
Thank for for clarifying. 

My point of view is that you should stick on correct dans despite the home app cannot managed it. It should come on a near future. I’m’personally use the Home+ which is a good reference. 

Maybe an alternative approche is to have a checkbox to choose which unit to expose like you do for KWh vs Watt?

Does all the API exposed data are exposed back  in HomeKit? What about consumption and difference between production and consumption?

thanks again.

**Comment by ecoen66** [comment]
You cannot arbitrarily choose what to publish to HomeKit.  You need to publish to a specific type of control - in this case, a light meter.  I will not be attempting to change this.

I also do not have an inverter with metering.  So, I won't be adding consumption or storage numbers.

However, anyone is free to fork my GitHub repository and add any features that they want.
