### ISSUE TITLE
dealing with Solaredge API request limit

### ISSUE THREAD

**Issue by stibbzy** [ecoen66/homebridge-solaredge-inverter#3]
Thanks for the plugin! Quick question. I have made similar plugins for the Vera HA controller, it pulls from CurrentPowerFlow, energyDetails, and storageData. 

For each of these, I’ve had to specify some fairly long (10min) request intervals to stay under the Solaredge API limit of 300 requests a day. I’m looking at moving away from Vera and I would rather use the Homebridge solution here (and try to add in the extra storage and site energy bits). But I’ve had a look at the code and can’t see anywhere where you specify a request limit. 

I know nothing about Homebridge; is it the case that a query to the API is only made when a user actually interacts with the Home app or Siri?

Cheers, Stibbzy.

**Comment by ecoen66** [comment]
@stibbzy  I did not bother to worry about the request limit in my plugin.  Apple Homekit only appears to query Homebridge/my plugin/the Solaredge API when a user actually interacts with the Home app or Siri.

As for accessing the additional information in CurrentPowerFlow, energyDetails, and storageData, you may want to check out the Homebridge plugin that @stepir created from my code at https://github.com/stepir/homebridge-solaredge .  He added the info from CurrentPowerFlow.
