### ISSUE TITLE
Incorrect lux value

### ISSUE THREAD

**Issue by VSavane** [ecoen66/homebridge-solaredge-inverter#5]
Current light level always reports as 0.0001 lux

What info can I provide to help troubleshoot this?

**Comment by ecoen66** [comment]
Can you send me the output from the following URL (replacing <siteID> and <apiKey> with your appropriate values when requesting):
https://monitoringapi.solaredge.com/site/<siteID>/overview?api_key=<apiKey>

**Comment by VSavane** [comment]
It would seem to be...

"This page contains the following errors:

error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error."

With a blank page thereafter.
 To confirm: https://monitoringapi.solaredge.com/site/SITE_NAME/overview?api_key=7_DIGIT-NUMBER
