### ISSUE TITLE
batteryPercentageState?

### ISSUE THREAD

**Issue by colseven** [ecoen66/homebridge-solaredge-inverter#7]
hi,
thanks for the plugin and the update, can you add batteryPercentageState from the API? then i can see my battery.

**Comment by ecoen66** [comment]
I can try.  However, I don't have a SolarEdge system with a battery, so I cannot test it.  That means that you would have to be willing to test it.  If that's the case, contact me at ecoen@yahoo.com and I will share the files with you to copy onto your homebridge to test it for me.
-Ed

    On Monday, November 2, 2020, 5:12:52 AM CST, colseven <notifications@github.com> wrote:  
 
 


hi,
thanks for the plugin and the update, can you add batteryPercentageState from the API? then i can see my battery.

**Comment by ecoen66** [comment]
New index.js and config.schema.json files sent.  Let me know if it works for you.

**Comment by ecoen66** [comment]
Feature tested and committed in version 0.1.3.
