### ISSUE TITLE
Does not show the correct value for Last Year and Life Time in Telephone

### ISSUE THREAD

**Issue by czarnyolek** [ecoen66/homebridge-solaredge-inverter#8]
Hello

Thank you for this plugin.
In Log Dispaly Homebridge  show good value: all,   but in Homekit when I have more 10000 (LUX = KW) I see in Homekit only 10000, not more. In my case, it concerns the Last Year and Life Time where I have: 

 lifeTimeData: { energy: 10450523, revenue: 3768.1284 },
  lastYearData: { energy: 10448918 }
![Zrzut ekranu 2020-11-04 o 10 00 21](https://user-images.githubusercontent.com/73824234/98090810-d996ff00-1e84-11eb-83ab-5e763ccd46b6.png)

**Comment by ecoen66** [comment]
Unfortunately, this is a limitation in the way that Apple's homeKit represents a LUX value over 10,000 -- It just rounds the value up to the next thousand.  After 100,000 it rounds to just the hundred thousands (so 138,432 = 100,000).
